openapi: 3.0.0
info:
  title: User API
  description: API to manage user data.
  version: 1.0.0

paths:
  /users:
    post:
      summary: Create a new user.
      description: Creates a new user with the provided details.
      operationId: createUser
      requestBody:
        description: User details to create a new user.
        content:
          application/json:
            schema:
              type: object
              properties:
                uuid:
                  type: string
                  example: "123e4567-e89b-12d3-a456-426614174000"
                email:
                  type: string
                  format: email
                  example: user@gmail.com
                name:
                  type: string
                  example: Username
                urlProfilePhoto:
                  type: string
                  format: uri
                  example: https://firebasestorage.googleapis.com/v0/profile_picture_user.jpg
                provider:
                  type: string
                  example: google.com
              required:
                - email
                - name
                - provider
                - uuid
      responses:
        '201':
          description: User created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '409':
          description: Email or UUID already exists.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ERROR_CREATE_USER"
              examples:
                EMAIL_ERROR:
                  value:
                    message: Duplicated Email
                    error: Conflict
                    statusCode: 409              
                UUID_ERROR:
                  value:
                    message: Duplicated UUID
                    error: Conflict
                    statusCode: 409  
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
                  error:
                    type: string
                    example: "Internal Server Error"
                  statusCode:
                    type: integer
                    example: 500
    get:
      summary: Retrieve all users.
      description: Returns a list of all users.
      operationId: getAllUsers
      responses:
        '200':
          description: List of users retrieved successfully.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserPublic'
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
                  error:
                    type: string
                    example: "Internal Server Error"
                  statusCode:
                    type: integer
                    example: 500

  /users/{user_uuid}:
    get:
      summary: Get user by UUID.
      description: Retrieves user information by UUID.
      operationId: getUserByUuid
      parameters:
        - in: path
          name: user_uuid
          required: true
          description: UUID of the user to retrieve.
          schema:
            type: string
            example: "123e4567-e89b-12d3-a456-426614173210"
      responses:
        '200':
          description: User found successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User not found"
                  error:
                    type: string
                    example: "Not Found"
                  statusCode:
                    type: integer
                    example: 404
        '505':
          description: Server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Server error"
                  error:
                    type: string
                    example: "Internal Server Error"
                  statusCode:
                    type: integer
                    example: 505

  /users/{user_uuid}/location:
    patch:
      summary: Update user location.
      description: Updates the latitude and longitude for a user based on their ID.
      operationId: updateUserLocation
      parameters:
        - in: path
          name: user_uuid
          required: true
          description: UUID of the user to update.
          schema:
            type: string
            example: "123e4567-e89b-12d3-a456-426614174000"
      requestBody:
        description: Location data to update the user's location.
        content:
          application/json:
            schema:
              type: object
              properties:
                latitude:
                  type: number
                  format: float
                  example: 34.6037
                longitude:
                  type: number
                  format: float
                  example: 58.3816
              required:
                - latitude
                - longitude
      responses:
        '200':
          description: User location updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User not found"
                  error:
                    type: string
                    example: "Not Found"
                  statusCode:
                    type: integer
                    example: 404
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
                  error:
                    type: string
                    example: "Internal Server Error"
                  statusCode:
                    type: integer
                    example: 500

  /users/{user_email}/failed-attempts:
    patch:
      summary: Increment the number of failed login attempts for a user.
      description: Increases the failed login attempt counter and locks the account if needed.
      operationId: increaseFailedAttempts
      parameters:
        - in: path
          name: user_email
          required: true
          description: Email of the user to update failed attempts.
          schema:
            type: string
            example: "user@gmail.com"
      responses:
        '200':
          description: Failed attempts updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User not found"
        '403':
          description: Account is locked due to multiple failed attempts.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Account is locked due to multiple failed attempts"
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Internal server error"
                  error:
                    type: string
                    example: "Internal Server Error"
                  statusCode:
                    type: integer
                    example: 500

  /users/{user_email}/check-lock-status:
    get:
      summary: Check if a user's account is locked.
      description: Returns lock status of the user account.
      operationId: checkLockStatus
      parameters:
        - in: path
          name: user_email
          required: true
          description: email of the user to check.
          schema:
            type: string
            example: "user@gmail.com"
      responses:
        '200':
          description: Lock status retrieved successfully.
          content:
            application/json:
              schema: 
                $ref: "#/components/schemas/ACCOUNT_LOCKING_MESSAGES"
              examples:
                ACCOUNT_NOT_LOCKED:
                  value:
                    message: Account is not locked
                    isLocked: 0
                    lockedDate: null
                ACCOUNT_LOCKED:
                  value:
                    message: Account is locked
                    isLocked: 1
                    lockedDate: 2025-04-17T07:00:20.549Z
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User not found"
                  isLocked:
                    type: integer
                    example: -1
        '500':
          description: Error checking lock status.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Error checking lock status"
                  isLocked:
                    type: integer
                    example: -1
  /users/{uuid}:
    patch:
      summary: Update user profile information.
      description: Updates the profile details of an existing user by UUID.
      operationId: updateProfileInfo
      parameters:
        - name: uuid
          in: path
          required: true
          description: UUID of the user to update.
          schema:
            type: string
            example: "123e4567-e89b-12d3-a456-426614174000"
      requestBody:
        description: Fields to update in the user's profile.
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateUserProfile'
      responses:
        '200':
          description: User updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
              example:
                uuid: "123e4567-e89b-12d3-a456-426614174000"
                email: updated.user@gmail.com
                name: Updated Name
                urlProfilePhoto: https://firebasestorage.googleapis.com/v0/new_photo.jpg
                provider: google.com
                latitude: 40.7128
                longitude: -74.0060
                failedAttempts: 0
                accountLocked: false
                lockUntil: null
                lastFailedAt: null
                description: "Updated profile description"
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: User not found
                error: Not Found
                statusCode: 404
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Internal server error
                error: Internal Server Error
                statusCode: 500
  /users/{uuid}/lock-status:
    patch:
      summary: Update user lock status.
      description: Allows an admin to lock or unlock a user's account.
      operationId: updateUserLockStatus
      parameters:
        - name: uuid
          in: path
          required: true
          description: UUID of the user to lock/unlock.
          schema:
            type: string
            example: "DcRx7dtmKKRKlcEyPff1IiwwI2h1"
      requestBody:
        description: Object indicating whether the account should be locked.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                accountLockedByAdmins:
                  type: boolean
                  example: true
              required:
                - accountLockedByAdmins
      responses:
        '200':
          description: User lock status updated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: User not found
                error: Not Found
                statusCode: 404
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /auth/google:
    patch:
      summary: Validate google token.
      description: Validates google token.
      operationId: loginWithGoogle
      requestBody:
          description: User details to create a new user.
          content:
            application/json:
              schema:
                type: object
                properties:
                  idToken:
                    type: string
                    example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1aWQiOiIxMjM0NTY3ODkwIiwibmFtZSI6IlRlc3QgVXNlciIsImVtYWlsIjoidGVzdEBleGFtcGxlLmNvbSIsImlhdCI6MTY4MzIzMzAwMCwiZXhwIjoxNjgzMjM2NjAwfQ.sD9gN0gUQJkjMvHe8FAH8DqvAPqH_3v0YzDwFg2nFGBzLGzR6lUcDL2j9Lb9iY2cXuZDJ4RfsXeY5VfYgWDvsc7tw7yRcFZxV1MjAJebdSxVX3OvwzKJj57Ff4uRzUEYyEZVfL3zRwdY3CW2KnMW4C2v43VpFCdKo3M2fNcd9q8M4lU9Fg2XPab4hP2aAZuGz7RzRzMGhMGjPoST4FZ8qGpYpK1t5RzqzGvP5cGgZz9XKZj3L5YgHjM3sZtYWfHzqNVXhv3F6KpKxDZv4LrFd3YcKdY7TfAzP6HfXrMq8D2c3tX7RpTyNqTfRLmJWz4BhvK6zC2HFzJHfWP9wKvh5rT7xWJrCqT4D7mWxqZyHtL4"
                required:
                  - idToken
      responses:
        '200':
          description: Token validated successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserGoogle'
        '401':
          description: Unauthorized - Invalid or missing token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Error validating token
                error: Unauthorized
                statusCode: 401
        '500':
          description: Internal server error.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                message: Internal server error
                error: Internal Server Error
                statusCode: 500
components:
  schemas:
    ACCOUNT_LOCKING_MESSAGES:
      type: object
      properties:
        message:
          type: string
        isLocked:
          type: integer
        lockedDate:
            type: string
            format: date-time
            nullable: true
    ERROR_CREATE_USER: 
      type: object
      properties:
        message:
          type: string                       
        error:
          type: string
        statusCode:
          type: integer
    User:
      type: object
      properties:
        uuid:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        email:
          type: string
          format: email
          example: user@gmail.com
        name:
          type: string
          example: Username
        urlProfilePhoto:
          type: string
          format: uri
          example: https://firebasestorage.googleapis.com/v0/profile_picture_user.jpg
        provider:
          type: string
          example: google.com
        latitude:
          type: number
          format: float
          nullable: true
          example: 34.6037
        longitude:
          type: number
          format: float
          nullable: true
          example: 58.3816
        failedAttempts:
          type: integer
          example: 3
        accountLocked:
          type: boolean
          example: true
        lockUntil:
          type: string
          format: date-time
          nullable: true
          example: "2025-04-13T12:00:00Z"
        lastFailedAt:
          type: string
          format: date-time
          nullable: true
          example: "2025-04-12T14:00:00Z"
        description:
          type: string
          example: ""
        accountLockedByAdmins:
          type: boolean
          example: false
    UserPublic:
      type: object
      properties:
        uuid:
          type: string
          example: "123e4567-e89b-12d3-a456-426614174000"
        email:
          type: string
          format: email
          example: user@gmail.com
        name:
          type: string
          example: Username
        urlProfilePhoto:
          type: string
          format: uri
          example: https://firebasestorage.googleapis.com/v0/profile_picture_user.jpg
        description:
          type: string
          example: "My description"
        createdAt:
          type: string
          format: date-time
          nullable: true
          example: "2025-05-11T23:44:53.936Z"
        accountLockedByAdmins:
          type: boolean
          example: false
    UpdateUserProfile:
      type: object
      properties:
        name:
          type: string
          example: Updated Name
        email:
          type: string
          format: email
          example: updated.user@gmail.com
        urlProfilePhoto:
          type: string
          format: uri
          example: https://firebasestorage.googleapis.com/v0/new_photo.jpg
        description:
          type: string
          example: "Updated profile description"
    ErrorResponse:
      type: object
      properties:
        message:
          type: string
          example: "Internal server error"
        error:
          type: string
          example: "Internal Server Error"
        statusCode:
          type: integer
          example: 500
    UserGoogle:
      type: object
      properties:
        id:
          type: string
          example: "117892345678901234567"
        email:
          type: string
          format: email
          example: user@gmail.com
        name:
          type: string
          example: Username
        picture:
          type: string
          format: uri
          example: https://lh3.googleusercontent.com/a-/AOh14GikYz8xO8q12345z7fpFZ_abcde=w96-c
       